.eslintrc.json
src/Button/Button.styles.ts
src/TableDownloadButton/TableDownloadButton.stories.tsx
src/TableDownloadButton/TableDownloadButton.styles.ts
src/TableDownloadButton/TableDownloadButton.tsx
src/TableDownloadButton/index.tsx
src/index.tsx

the base styles for the tableDownloadButton Component

Add table download button

---

.github/CODEOWNERS
docs/pull_request_template.md

Adding code owners and PR template.

Add code owners and PR template

---

.github/labels.json
.github/workflows/approval_label.yml
.github/workflows/default_labels.yml

Ticket: no ticket
Why this is needed: parity with maps project
Link to Figma doc: 🙈

making labels work the same as maps

---

.github/workflows/approval_label.yml

Ticket: nope
Why this is needed: Seems like there was a missing opening quotation mark.
Link to Figma doc: nope

Update approval label workflow

---

src/Popover/Popover.stories.tsx
src/Popover/Popover.styles.ts
src/Popover/Popover.tsx

Ticket:
Why this is needed: need to be able to control onclick on popover options

add onclick to popover

---

package.json
src/index.tsx

Ticket:
Why this is needed: some little forgotten components were lonely

Export forgotten components

---

example/src/App.js
package.json
src/DropDown/DropDown.stories.mdx
src/DropDown/DropDown.styles.ts
src/DropDown/DropDown.tsx

Ticket: No ticket
Why this is needed: Add initial selected item to dropdown and update styles so the list doesn't push content around the page.
Link to Figma doc: nope

Update dropdown component with initial selected item and some styles

---

package.json
src/DropDown/DropDown.styles.ts
src/ToggleGroup/ToggleGroup.stories.mdx
src/ToggleGroup/ToggleGroup.tsx

Ticket:
Why this is needed: Make ToggleGroup controllable.

Make toggle controlled, update dropdown pointer

---

src/Switch/Switch.styles.js

Ticket:
Why this is needed: MIssed this first time around

Primary color switch

---

package.json
src/Switch/Switch.tsx

Test ID for switch

---

example/package.json
example/yarn.lock

Make sure there is only one react included when in dev

---

yarn.lock

Import old yarn lock file

---

docs/pull_request_template.md

Ticket / Why this is needed: I always forget to bnmp the version. Also generally a piece of work should have a ticket OR a why it was done. the ticket is normally the WHY

Adjust PR template

---

README.md

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Not needed.
Ticket / Why this is needed: Testing delopy previews for Netlify storybook build.

Testing PR deploy preview build

---

package.json
src/NotificationBar/NotificationBar.stories.mdx
src/NotificationBar/NotificationBar.styles.ts

Ticket / Why this is needed: Based on our conversationm moved some styling to the bar component

Move notification bar styling

---

package.json
src/defaultTheme.ts

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Yup
Ticket / Why this is needed: Nope
Link to Figma doc: nope
Extra large we removed from scss vars so need to add it here for the autocomplete list

add extra large shadow

---

package.json
src/TableDownloadButton/TableDownloadButton.styles.ts

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Yup
Ticket / Why this is needed: Nope
Link to Figma doc: Nope
@zac-robinson This will help with the buttons fitting into the new updates to the table.

make table buttons more reactive to their parent element

---

package.json
src/NotificationBar/NotificationBar.stories.mdx
src/NotificationBar/NotificationBar.styles.ts
src/NotificationBar/NotificationBar.tsx

Ticket / Why this is needed: https://edozohq.atlassian.net/browse/MAPS-540
Link to Figma doc: https://www.figma.com/file/EcJBkyjEjD5ibjCYT7rxxe/Spinner?node-id=13%3A1916
I have numbered this 10.10 because it will go in befor ethe PR that is already approved. I will update that PR when it comes to getting it in.

add warning colours for notification bar

---

.eslintrc.json
package.json
src/Badge/Badge.styles.ts
src/Button/Button.styles.ts
src/DisplayBox/DisplayBox.styles.ts
src/DropDown/DropDown.styles.ts
src/Icons/Icons.tsx
src/List/List.styles.ts
src/List/ListItem.styles.ts
src/NotificationBar/NotificationBar.styles.ts
src/PopoverContent/PopoverContent.styles.ts
src/PriceIndicator/PriceIndicator.styles.ts
src/Switch/Switch.styles.js
src/TableDownloadButton/TableDownloadButton.styles.ts
src/Tabs/Panel.styles.tsx
src/Tabs/Tab.styles.tsx
src/ThemeProvider.tsx
src/ToggleGroup/ToggleGroup.styles.ts
src/Typography/Typography.stories.mdx
src/Typography/Typography.styles.ts
src/Typography/Typography.tsx
src/Typography/index.tsx
src/defaultTheme.ts
src/globalStyle.storybook.ts
src/globalStyle.ts
src/styled.d.ts

Ticket / Why this is needed: https://edozohq.atlassian.net/browse/MAPS-85, https://edozohq.atlassian.net/browse/MAPS-86, https://edozohq.atlassian.net/browse/MAPS-250
Link to Figma doc: https://www.figma.com/file/OpCqZzeuBbb8NBshcsBRpc/Edozo-maps-DS?node-id=554%3A3

tech/theme styles tweaks, typography and debugging improvement

---

package.json
src/NotificationBar/NotificationBar.styles.ts

fix notification colours

---

package.json
src/Tooltip/Tooltip.tsx

set tooltip default options

---

package.json
src/Icons/Icons.stories.mdx
src/Icons/Icons.tsx
src/Icons/icons/H-mark.svg
src/Icons/icons/T-mark.svg
src/defaultTheme.ts

Ticket / Why this is needed: https://edozohq.atlassian.net/browse/MAPS-268
Link to Figma doc: https://www.figma.com/file/k5TF6XQ0tpXIOvLIVaeBvR/Drawing-library?node-id=135%3A2021

Add drawing lib icons

---

package.json
yarn.lock

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? not needed

Bump styled components

---

package.json
src/NotificationBar/NotificationBar.tsx
src/Tooltip/Tooltip.tsx
yarn.lock

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? yes
Ticket / Why this is needed: React element is the wrong type i think. ReactNode covers ReactElement as well as string boolean number undefined

Change TS types

---

package.json
src/DropDown/DropDown.tsx

Ticket / Why this is needed: need this for https://edozohq.atlassian.net/browse/MAPS-925 but good to have it anyway

Add arg to onChange method

---

package.json
src/DropDown/DropDown.tsx

Tweak dropdown value type

---

README.md

Add release instructions to readme

---

package.json
yarn.lock

removed the `-s` flag as we aren't using it: https://storybook.js.org/docs/react/api/cli-options

bump storybook version

---

package.json
yarn.lock

updage storybook

---

package.json
src/DropDown/DropDown.tsx
yarn.lock

- update main and peer deps
Doesn't feel like it needs a version bump

bump peer and main deps

---

package.json
src/defaultTheme.ts

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Y
Ticket / Why this is needed: No ticket, I had a conversation with Sylvia about this and she said to put it back 4px, I was having issues getting buttons...etc... to look correct so it is going back to 4px until she reviews it again.

update spacing value

---

package.json
src/Popover/Popover.stories.tsx
src/Popover/Popover.styles.ts
src/globalStyle.ts

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Y
Ticket / Why this is needed: It took me a while to figure out how to do this so thought i'd pop in a story to document it as we will probably need to do it a fair bit.
Also changed how the padding for the content is set, having the component not set it is best practise so the developer using the lid can decide how it looks rather than having the 8px p[adding force(ish) on them by the lib.
I am also coming to the realisation that the global styles should live at the app level not in the UI lib, but that should be another PR.

add new popover story

---

package.json
src/Switch/Switch.tsx

Try checkbox role again

---

package.json
src/Icons/Icons.stories.tsx
src/Icons/Icons.tsx
src/Icons/icons/arrow-mark.svg
src/Icons/icons/cross-mark.svg

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? yes
**Ticket / Why this is needed:**
Adding in the Cross and Arrow icons
Arrow
https://edozohq.atlassian.net/browse/MAPS-1149?atlOrigin=eyJpIjoiYzkzOTE1ZjdhMjBjNDFlZjlhY2VjMWEwYjU5N2JmYWMiLCJwIjoiaiJ9
Cross
https://edozohq.atlassian.net/browse/MAPS-1004?atlOrigin=eyJpIjoiYzYzMjhlYTI4ZjlmNGUxYThlZWMwNTA3OTU4NmEzM2YiLCJwIjoiaiJ9
**Link to Figma doc:**
Arrow
https://www.figma.com/file/k5TF6XQ0tpXIOvLIVaeBvR/Drawing-library?node-id=418%3A44191
Cross
https://www.figma.com/file/k5TF6XQ0tpXIOvLIVaeBvR/Drawing-library?node-id=222%3A323

Feature/add Arrow and Cross mark icons

---

.github/CODEOWNERS

Add CB to codeowners here too

---

package.json
src/Icons/Icons.tsx

Silly TS error

---

package.json
src/List/ListItem.styles.ts
src/List/ListItem.tsx
src/TableDownloadButton/TableDownloadButton.tsx

Ticket / Why this is needed: Some work I am doing in maps needs to have full HTML attributes on the mech wombat elements. Might need to be mroe soon

use some html props

---

package.json
src/List/ListItem.styles.ts
src/TableDownloadButton/TableDownloadButton.tsx

Ticket / Why this is needed: Missed a couple here

add additional props

---

package.json
src/ButtonV2/ButtonV2.stories.tsx
src/ButtonV2/ButtonV2.styles.ts
src/ButtonV2/ButtonV2.tsx
src/ButtonV2/index.tsx
src/index.tsx

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? 👍 
https://edozohq.atlassian.net/browse/OP-153?atlOrigin=eyJpIjoiZGMyOTBhMWY2MzhkNGQ3OTkyZDYzYjQzOGQzYzFhZGEiLCJwIjoiaiJ9
We need to move this into wombat for OP so that It can in the future be used in Maps

Tech/ Move OP button into Wombat

---

package.json
src/Collapse/Collapse.tsx

Ticket / Why this is needed: When trying to fix the flaky tests I was getting an error that a component was updating after it had been unmounted and I am pretty sure it is this

Stop updating unmounted component

---

package.json
src/index.tsx

Export global search

---

package.json
src/DisplayBox/DisplayBox.styles.ts
src/InputGroup/InputGroup.tsx
src/defaultTheme.ts
src/styled.d.ts

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Yup
Ticket / Why this is needed: No ticket. Adding some base breakpoints, we can tweak the values in future to marry-up with design (I am going to talk to SC about a strategy for making this easier for us). For now I have taken the base values from tailwind as I know the team have talked about it so it seems like a decent place to start (rather than me plucking numbers out of my head).
Example usage in `src/DisplayBox/DisplayBox.styles.ts` which isn't exposed to the apps that consume the lib.

Add breakpoints

---

package.json
src/Tabs/Tab.tsx

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Y
Ticket / Why this is needed: Converting a file in maps to TS highlighted the type was wrong

Tweak type of tab prop

---

src/List/List.styles.ts
src/List/List.tsx
src/List/ListContext.tsx
src/List/ListItem/ListItem.tsx

Fix circular dep on list

---

.storybook/preview.js
package.json
src/InputGroup/Button/Button.tsx
src/InputGroup/Button/index.ts
src/InputGroup/GlobalSearch.tsx
src/InputGroup/Input/Input.styles.ts
src/InputGroup/Input/Input.tsx
src/InputGroup/Input/index.ts
src/InputGroup/InputGroup.stories.tsx
src/InputGroup/InputGroup.styles.ts
src/InputGroup/InputGroup.tsx
src/InputGroup/InputGroupContext.ts
src/InputGroup/Item/Item.styles.ts
src/InputGroup/Item/index.ts
src/InputGroup/Textarea/Textarea.styles.ts
src/InputGroup/Textarea/Textarea.tsx
src/InputGroup/Textarea/index.ts

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Yes
Start of getting our inputs into UI lib - and global search.
There is a corresponding PR on OP (https://github.com/edozo/edozo-occupier-plans-fe/pull/122) so you can easily try this locally.

Op 221 use global search component in my plans

---

package.json
src/DropDown/DropDown.tsx

Ticket / Why this is needed: Needed to change this for a 
dropdown that doesn't have text in

Change dropdown label type

---

package.json
src/Header/AppHeader.tsx
src/Header/ProductSwitch/ProductSwitch.tsx

Ticket / Why this is needed: This will allow us to disable a product if 
a user doesn't have access

Disable product selector from each app

---

package.json
src/Header/ProductSwitch/ProductSwitch.styles.ts
src/Header/ProductSwitch/ProductSwitch.tsx

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Yes
Ticket / Why this is needed: [MAPS-2221](https://edozohq.atlassian.net/browse/MAPS-2221)

Remove new from product switch

---

package.json
src/InputGroup/GlobalSearch.tsx
src/InputGroup/Input/Input.styles.ts
src/InputGroup/Input/Input.tsx
src/InputGroup/InputGroup.stories.tsx
src/InputGroup/InputGroup.tsx
src/InputGroup/InputGroupContext.ts
src/InputGroup/Textarea/Textarea.styles.ts
src/InputGroup/Textarea/Textarea.tsx

Update input to work with numbers

---

README.md

I found when working on this project for the first time, it was a little confusing. 
I've added a few more hints to the Readme, and changed the structure a little to help future developers.

Update the readme with additional details

---

.gitignore
package.json
src/Icons/Icons.stories.tsx
src/Icons/Icons.tsx
src/Icons/icons/actions-indicator.svg

add actions icon

---

package.json
src/Header/AppHeader.tsx
src/Header/Header.tsx
src/Header/ProductSwitch/ProductSwitch.styles.ts

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Yes
Ticket / Why this is needed: [MAPS-2727](https://edozohq.atlassian.net/browse/MAPS-2727)

Add reports to product switcher

---

package.json
src/Header/Menu/MenuItem.styles.ts
src/defaultTheme.ts
src/styled.d.ts

BEFORE CREATING THIS PR, have you bumped the package JSON where appropriate? Yes

Add appColor for Reports to update the header colours

---

package.json
src/DropDown/DropDown.styles.ts
src/Header/PlatformMenu/PlatformButton.styles.ts
src/InputGroup/Button/Button.styles.ts
src/InputGroup/Input/Input.styles.ts
src/InputGroup/Input/Input.tsx
src/InputGroup/InputGroup.styles.ts
src/InputGroup/InputGroup.tsx
src/InputGroup/Textarea/Textarea.styles.ts
src/InputGroup/Textarea/Textarea.tsx
src/Popover/Popover.styles.ts
src/ToggleGroup/ToggleGroup.styles.ts

Fix some issues with styled components update

---

package.json
src/ButtonV2/ButtonV2.styles.ts
src/EdozoLogo/EdozoLogo.styles.ts
src/Header/Menu/MenuItem.styles.ts
src/List/ListItem/ListItem.styles.ts
yarn.lock

Fix broken styles in product selector

---

package.json
src/InputGroup/GlobalSearch.tsx
src/InputGroup/InputGroup.stories.tsx

BEFORE CREATING THIS PR, have you bumped the package JSON where 
appropriate? yup
Ticket / Why this is needed: n/a
Link to Figma doc: n/a
This is probably not the ideal way to do this but it should do the job for 
now. Screenshot shows the warning this will fix when pulled into the apps

use name with global search component
